= NISO JATS Ruby library

The `niso-jats` library is a parser and generator for NISO JATS XML documents.

It is intended to be used to parse and generate NISO JATS XML v1.2 documents.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'niso-jats'
----

And then execute:

[source]
----
$ bundle install
----

Or install it yourself as:

[source]
----
$ gem install niso-jats
----


== Usage

=== Parsing a NISO JATS XML document

[source,ruby]
----
require 'niso/jats'

article = Niso::Jats::Article.from_xml(File.read('article.xml'))
----

=== Extracting bibliographic data

The `Article` class provides convenience methods for common lookups:

[source,ruby]
----
article.journal_title   # => "Metrologia"
article.doi             # => "10.1088/0026-1394/52/1/155"

article.contributors
# => [#<Niso::Jats::Contrib>, #<Niso::Jats::Contrib>, ...]

article.affiliation("aff1")
# => [#<Niso::Jats::Aff>]

article.pub_dates
# => ["2015-02-01", "2015-01-30"]

article.locality
# => [["volume", "52"], ["issue", "1"], ["page", "155", "162"]]

article.doi_links
# => [{ content: "https://doi.org/10.1088/0026-1394/52/1/155", type: "src" },
#     { content: "https://doi.org/10.1088/0026-1394/52/1/155", type: "doi" }]
----

=== Working with contributors

The `Contrib` class provides filtering on cross-references:

[source,ruby]
----
contrib = article.contributors.first
contrib.aff_xrefs   # => [#<Niso::Jats::Xref ref_type="aff" rid="aff1">]
----

=== Generating a NISO JATS XML document

[source,ruby]
----
puts article.to_xml(declaration: true, encoding: "utf-8")
----


== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/metanorma/niso-jats.


== Copyright and license

The gem is available as open source under the terms of the BSD 2-clause license.

All rights reserved. Ribose

